-- LINES
INSERT INTO line (line_id, line_name, line_color) VALUES (1, '1호선', '#E53E3E');
INSERT INTO line (line_id, line_name, line_color) VALUES (2, '2호선', '#38A169');
INSERT INTO line (line_id, line_name, line_color) VALUES (3, '3호선', '#DD6B20');

-- STATIONS: LINE 1
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1001, '설화명곡', 'L1-01', 1, 1, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1002, '화원', 'L1-02', 1, 2, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1003, '대곡', 'L1-03', 1, 3, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1004, '진천', 'L1-04', 1, 4, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1005, '월배', 'L1-05', 1, 5, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1006, '상인', 'L1-06', 1, 6, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1007, '월촌', 'L1-07', 1, 7, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1008, '송현', 'L1-08', 1, 8, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1009, '서부정류장', 'L1-09', 1, 9, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1010, '대명', 'L1-10', 1, 10, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1011, '안지랑', 'L1-11', 1, 11, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1012, '현충로', 'L1-12', 1, 12, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1013, '영대병원', 'L1-13', 1, 13, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1014, '교대', 'L1-14', 1, 14, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1015, '명덕', 'L1-15', 1, 15, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1016, '반월당', 'L1-16', 1, 16, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1017, '중앙로', 'L1-17', 1, 17, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1018, '대구역', 'L1-18', 1, 18, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1019, '칠성시장', 'L1-19', 1, 19, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1020, '신천', 'L1-20', 1, 20, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1021, '동대구', 'L1-21', 1, 21, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1022, '동구청', 'L1-22', 1, 22, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1023, '아양교', 'L1-23', 1, 23, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1024, '동촌', 'L1-24', 1, 24, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1025, '해안', 'L1-25', 1, 25, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1026, '방촌', 'L1-26', 1, 26, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1027, '용계', 'L1-27', 1, 27, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1028, '율하', 'L1-28', 1, 28, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1029, '신기', 'L1-29', 1, 29, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1030, '반야월', 'L1-30', 1, 30, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1031, '각산', 'L1-31', 1, 31, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1032, '안심', 'L1-32', 1, 32, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1033, '대구대', 'L1-33', 1, 33, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1034, '하양', 'L1-34', 1, 34, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (1035, '금호', 'L1-35', 1, 35, NULL, NULL);

-- STATIONS: LINE 2
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2001, '문양', 'L2-01', 2, 1, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2002, '다사', 'L2-02', 2, 2, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2003, '대실', 'L2-03', 2, 3, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2004, '강창', 'L2-04', 2, 4, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2005, '계명대', 'L2-05', 2, 5, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2006, '성서산업단지', 'L2-06', 2, 6, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2007, '이곡', 'L2-07', 2, 7, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2008, '용산', 'L2-08', 2, 8, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2009, '죽전', 'L2-09', 2, 9, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2010, '감삼', 'L2-10', 2, 10, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2011, '두류', 'L2-11', 2, 11, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2012, '내당', 'L2-12', 2, 12, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2013, '반고개', 'L2-13', 2, 13, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2014, '청라언덕', 'L2-14', 2, 14, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2015, '반월당', 'L2-15', 2, 15, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2016, '경대병원', 'L2-16', 2, 16, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2017, '대구은행', 'L2-17', 2, 17, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2018, '범어', 'L2-18', 2, 18, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2019, '수성구청', 'L2-19', 2, 19, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2020, '만촌', 'L2-20', 2, 20, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2021, '담티', 'L2-21', 2, 21, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2022, '연호', 'L2-22', 2, 22, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2023, '수성알파시티', 'L2-23', 2, 23, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2024, '고산', 'L2-24', 2, 24, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2025, '신매', 'L2-25', 2, 25, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2026, '사월', 'L2-26', 2, 26, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2027, '정평', 'L2-27', 2, 27, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2028, '임당', 'L2-28', 2, 28, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (2029, '영남대', 'L2-29', 2, 29, NULL, NULL);

-- STATIONS: LINE 3
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3001, '칠곡경대병원', 'L3-01', 3, 1, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3002, '학정', 'L3-02', 3, 2, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3003, '팔거', 'L3-03', 3, 3, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3004, '동천', 'L3-04', 3, 4, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3005, '칠곡운암', 'L3-05', 3, 5, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3006, '구암', 'L3-06', 3, 6, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3007, '태전', 'L3-07', 3, 7, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3008, '매천', 'L3-08', 3, 8, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3009, '매천시장', 'L3-09', 3, 9, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3010, '팔달', 'L3-10', 3, 10, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3011, '공단', 'L3-11', 3, 11, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3012, '만평', 'L3-12', 3, 12, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3013, '팔달시장', 'L3-13', 3, 13, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3014, '원대', 'L3-14', 3, 14, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3015, '북구청', 'L3-15', 3, 15, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3016, '달성공원', 'L3-16', 3, 16, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3017, '서문시장', 'L3-17', 3, 17, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3018, '청라언덕', 'L3-18', 3, 18, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3019, '남산', 'L3-19', 3, 19, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3020, '명덕', 'L3-20', 3, 20, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3021, '건들바위', 'L3-21', 3, 21, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3022, '대봉교', 'L3-22', 3, 22, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3023, '수성시장', 'L3-23', 3, 23, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3024, '수성구민운동장', 'L3-24', 3, 24, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3025, '어린이세상', 'L3-25', 3, 25, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3026, '황금', 'L3-26', 3, 26, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3027, '수성못', 'L3-27', 3, 27, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3028, '지산', 'L3-28', 3, 28, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3029, '범물', 'L3-29', 3, 29, NULL, NULL);
INSERT INTO station (station_id, station_name, station_code, line_id, sequence_no, latitude, longitude) VALUES (3030, '용지', 'L3-30', 3, 30, NULL, NULL);

-- SECTIONS: LINE 1
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (1, 1001, 1002, 135, 1.2);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (2, 1002, 1003, 146, 1.3);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (3, 1003, 1004, 113, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (4, 1004, 1005, 90, 0.8);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (5, 1005, 1006, 79, 0.7);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (6, 1006, 1007, 101, 0.9);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (7, 1007, 1008, 113, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (8, 1008, 1009, 180, 1.6);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (9, 1009, 1010, 90, 0.8);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (10, 1010, 1011, 79, 0.7);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (11, 1011, 1012, 79, 0.7);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (12, 1012, 1013, 101, 0.9);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (13, 1013, 1014, 79, 0.7);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (14, 1014, 1015, 90, 0.8);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (15, 1015, 1016, 79, 0.7);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (16, 1016, 1017, 79, 0.7);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (17, 1017, 1018, 90, 0.8);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (18, 1018, 1019, 135, 1.2);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (19, 1019, 1020, 101, 0.9);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (20, 1020, 1021, 101, 0.9);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (21, 1021, 1022, 90, 0.8);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (22, 1022, 1023, 113, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (23, 1023, 1024, 113, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (24, 1024, 1025, 113, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (25, 1025, 1026, 124, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (26, 1026, 1027, 135, 1.2);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (27, 1027, 1028, 124, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (28, 1028, 1029, 113, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (29, 1029, 1030, 113, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (30, 1030, 1031, 101, 0.9);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (31, 1031, 1032, 113, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (32, 1032, 1033, 405, 3.6);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (33, 1033, 1034, 461, 4.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (34, 1034, 1035, 664, 5.9);

-- SECTIONS: LINE 2 (uniform 1.1km / 150s)
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (35, 2001, 2002, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (36, 2002, 2003, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (37, 2003, 2004, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (38, 2004, 2005, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (39, 2005, 2006, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (40, 2006, 2007, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (41, 2007, 2008, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (42, 2008, 2009, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (43, 2009, 2010, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (44, 2010, 2011, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (45, 2011, 2012, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (46, 2012, 2013, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (47, 2013, 2014, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (48, 2014, 2015, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (49, 2015, 2016, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (50, 2016, 2017, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (51, 2017, 2018, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (52, 2018, 2019, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (53, 2019, 2020, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (54, 2020, 2021, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (55, 2021, 2022, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (56, 2022, 2023, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (57, 2023, 2024, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (58, 2024, 2025, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (59, 2025, 2026, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (60, 2026, 2027, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (61, 2027, 2028, 150, 1.1);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (62, 2028, 2029, 150, 1.1);

-- SECTIONS: LINE 3 (uniform 1.0km / 140s)
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (63, 3001, 3002, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (64, 3002, 3003, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (65, 3003, 3004, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (66, 3004, 3005, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (67, 3005, 3006, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (68, 3006, 3007, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (69, 3007, 3008, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (70, 3008, 3009, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (71, 3009, 3010, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (72, 3010, 3011, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (73, 3011, 3012, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (74, 3012, 3013, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (75, 3013, 3014, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (76, 3014, 3015, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (77, 3015, 3016, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (78, 3016, 3017, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (79, 3017, 3018, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (80, 3018, 3019, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (81, 3019, 3020, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (82, 3020, 3021, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (83, 3021, 3022, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (84, 3022, 3023, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (85, 3023, 3024, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (86, 3024, 3025, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (87, 3025, 3026, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (88, 3026, 3027, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (89, 3027, 3028, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (90, 3028, 3029, 140, 1.0);
INSERT INTO station_section (section_id, from_station_id, to_station_id, duration_seconds, distance_km) VALUES (91, 3029, 3030, 140, 1.0);

-- TRANSFERS (single row per pair; RouteService treats bidirectionally)
INSERT INTO transfer_info (transfer_id, from_station_id, to_station_id, transfer_time_sec) VALUES (1, 1016, 2015, 180);
INSERT INTO transfer_info (transfer_id, from_station_id, to_station_id, transfer_time_sec) VALUES (2, 2014, 3018, 180);
INSERT INTO transfer_info (transfer_id, from_station_id, to_station_id, transfer_time_sec) VALUES (3, 1015, 3020, 180);

-- FARE POLICY
INSERT INTO fare_policy (fare_policy_id, min_distance_km, max_distance_km, base_fare) VALUES (1, 0, 10, 1250);
INSERT INTO fare_policy (fare_policy_id, min_distance_km, max_distance_km, base_fare) VALUES (2, 10, 30, 1450);
INSERT INTO fare_policy (fare_policy_id, min_distance_km, max_distance_km, base_fare) VALUES (3, 30, 999, 1650);

-- TIMETABLE sample: station 1001 (설화명곡) and 1016 (반월당), WEEKDAY UP_BOUND
INSERT INTO timetable (timetable_id, station_id, direction, day_type, departure_time, train_id) VALUES (1, 1001, 'UP_BOUND', 'WEEKDAY', '05:30:00', 'K101');
INSERT INTO timetable (timetable_id, station_id, direction, day_type, departure_time, train_id) VALUES (2, 1001, 'UP_BOUND', 'WEEKDAY', '08:00:00', 'K102');
INSERT INTO timetable (timetable_id, station_id, direction, day_type, departure_time, train_id) VALUES (3, 1001, 'UP_BOUND', 'WEEKDAY', '11:30:00', 'K103');
INSERT INTO timetable (timetable_id, station_id, direction, day_type, departure_time, train_id) VALUES (4, 1001, 'UP_BOUND', 'WEEKDAY', '15:00:00', 'K104');
INSERT INTO timetable (timetable_id, station_id, direction, day_type, departure_time, train_id) VALUES (5, 1001, 'UP_BOUND', 'WEEKDAY', '18:30:00', 'K105');
INSERT INTO timetable (timetable_id, station_id, direction, day_type, departure_time, train_id) VALUES (6, 1001, 'UP_BOUND', 'WEEKDAY', '23:30:00', 'K106');
INSERT INTO timetable (timetable_id, station_id, direction, day_type, departure_time, train_id) VALUES (7, 1016, 'UP_BOUND', 'WEEKDAY', '05:30:00', 'K107');
INSERT INTO timetable (timetable_id, station_id, direction, day_type, departure_time, train_id) VALUES (8, 1016, 'UP_BOUND', 'WEEKDAY', '08:00:00', 'K108');
INSERT INTO timetable (timetable_id, station_id, direction, day_type, departure_time, train_id) VALUES (9, 1016, 'UP_BOUND', 'WEEKDAY', '11:30:00', 'K109');
INSERT INTO timetable (timetable_id, station_id, direction, day_type, departure_time, train_id) VALUES (10, 1016, 'UP_BOUND', 'WEEKDAY', '15:00:00', 'K110');
INSERT INTO timetable (timetable_id, station_id, direction, day_type, departure_time, train_id) VALUES (11, 1016, 'UP_BOUND', 'WEEKDAY', '18:30:00', 'K111');
INSERT INTO timetable (timetable_id, station_id, direction, day_type, departure_time, train_id) VALUES (12, 1016, 'UP_BOUND', 'WEEKDAY', '23:30:00', 'K112');
